language: java

after_success:
    - ./gradlew jacocoTestReport
    - curl http://www.jpm4j.org/install/script > jpmInstall.sh
    - sudo sh jpmInstall.sh
    - sudo jpm install com.codacy:codacy-coverage-reporter:assembly
    - codacy-coverage-reporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml