language: java

after_success:
    - env
    - echo "####################"
    - echo $TEST_ENV
    - echo $TEST_ENV2
    - curl http://www.jpm4j.org/install/script > jpmInstall.sh
    - sudo sh jpmInstall.sh
    - sudo jpm install com.codacy:codacy-coverage-reporter:assembly
    - codacy-coverage-reporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml -t $COVERALLS_REPO_TOKEN